### ISSUE TITLE
com.googlecode.objectify.impl.TransactorNo transactNew: Optimistic concurrency failure for com.googlecode.luceneappengine.GaeLockFactory$1$1@1d01abc (retrying): java.util.ConcurrentModificationException: too much contention on these datastore entities. please try again.

### ISSUE THREAD

**Issue by Alchemist0823** [UltimaPhoenix/luceneappengine#7]
```
com.googlecode.objectify.impl.TransactorNo transactNew: Optimistic concurrency failure for com.googlecode.luceneappengine.GaeLockFactory$1$1@1d01abc (retrying): java.util.ConcurrentModificationException: too much contention on these datastore entities. please try again.
com.goodi.backend.search.IndexSearchService index: Error indexing content Document<stored,indexed,indexOptions=DOCS<id:5696381570252800> indexed,tokenized<author:Forrest Sunmm> indexed,tokenized<title:what is conversion rate> indexed,tokenized<content:what is conversion rate?> indexed,tokenized,indexOptions=DOCS<tags:business economics >>.
java.lang.NullPointerException
	at org.apache.lucene.util.BytesRef.<init>(BytesRef.java:84)
	at org.apache.lucene.store.DataOutput.writeString(DataOutput.java:260)
	at org.apache.lucene.store.DataOutput.writeStringStringMap(DataOutput.java:302)
	at org.apache.lucene.codecs.lucene50.Lucene50SegmentInfoFormat.write(Lucene50SegmentInfoFormat.java:140)
	at org.apache.lucene.index.DocumentsWriterPerThread.sealFlushedSegment(DocumentsWriterPerThread.java:495)
	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:456)
	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:503)
	at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:615)
	at org.apache.lucene.index.IndexWriter.doFlush(IndexWriter.java:2952)
	at org.apache.lucene.index.IndexWriter.flush(IndexWriter.java:2927)
	at org.apache.lucene.index.IndexWriter.shutdown(IndexWriter.java:965)
	at org.apache.lucene.index.IndexWriter.close(IndexWriter.java:1010)
```

**Comment by aabdolla** [comment]
I have been running into this error a lot as well.

**Comment by UltimaPhoenix** [comment]
This issue occurs when you are indexing simultaneously a lot of data. LAE works using the cpu power available into the google cloud environment so you must reconsider the available power thinking about the [Google Cloud Instance class ](https://cloud.google.com/appengine/docs/java/modules/#Java_Instance_scaling_and_class). For instance if you are using the F1 class you have only 600MHz for one indexing process, so it will take the time it needs to.
To avoid this problem you have multiple choice:
1. Design the indexing process of your app using [Task Queue](https://cloud.google.com/appengine/docs/java/taskqueue/), this is the best solution;
2. Upgrade your instance class to F2 or F4 (more power less starvation waiting for index).
3. If you have one big index you can split it into small pieces
4. Use the Google App Engine [Documents and Indexes ](https://cloud.google.com/appengine/docs/java/search/)

**Comment by aabdolla** [comment]
Thank you for the reply! I did end up putting my work into the Task Queue and it greatly reduced the error but I still got a few of them while indexing the 400 items I have. GAE Documents and Index don't support did you mean which is a shame so I am using Lucene for the suggester. I will try and upgrade the instance and see how that goes. Thank you again.

**Comment by UltimaPhoenix** [comment]
You are welcome. Just one more hint, try to set the [max-concurrent-requests](https://cloud.google.com/appengine/docs/java/config/queue) of the indexing queue to 1, doing it you should completely avoid any concurrency indexing issue, you can still have some problems querying the index during the job for sure. To resolve them you should fine tune the _rate_ and the _bucket-size_ of the indexing queue to appropriate values.
