### ISSUE TITLE
access denied ("java.lang.RuntimePermission" "modifyThreadGroup")

### ISSUE THREAD

**Issue by yelliver** [UltimaPhoenix/luceneappengine#8]
I have this in a web servlet:
```
        Analyzer analyzer = new StandardAnalyzer();
        Directory directory = new GaeDirectory();
        IndexWriterConfig config = new IndexWriterConfig(analyzer);
        IndexWriter iwriter = new IndexWriter(directory, config);
        Document doc = new Document();
        String text = "This is the text to be indexed";
        doc.add(new Field("fieldname", text, TextField.TYPE_STORED));
        iwriter.addDocument(doc);
        iwriter.close();
```
and I try to access this servlet on the browser, press F5 many times, it shows the error:
`access denied ("java.lang.RuntimePermission" "modifyThreadGroup")
at line iwriter.close();`

**Comment by UltimaPhoenix** [comment]
You should use the LAE specific `IndexWriterConfig`. Please follow [these instructions](https://github.com/UltimaPhoenix/luceneappengine/wiki/Usage-and-Configuration)

**Comment by yelliver** [comment]
Thank you very much, I did not read the instructions carefully, btw, do you have plan to upgrade to lucene 5.5.0? I saw many "coming soon" features and I am very excited about them. But 6 months pass

**Comment by UltimaPhoenix** [comment]
Yes, I'm working on it. Sorry but I'm very busy in this period. I have lots of updates to push into this repository but I'm checking them before doing it. I will try to complete and push it all before the end of the month.
